<a href="https://colab.research.google.com/github/cyber-241/2pic/blob/main/Untitle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
# Cài đặt thư viện (nếu chưa có)
!pip install numpy

# Import thư viện để sử dụng cho toàn bộ bài
import numpy as np
import pandas as pd

In [5]:

# Cách 1: Tạo từ Python list
my_list = [1, 9, 15, 39]
print('Python list:', my_list)

my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)

# Cách 2: Tạo trực tiếp
a = np.array([1, 9, 15, 39])
print(a)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]


In [14]:
c = np.array([(1, 2, 3),
              (4, 5, 6)
             ])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [15]:
d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
print(d)
print("Kích thước:", d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
Kích thước: (2, 2, 3)


In [16]:
e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix:\n', e)
print('One matrix:\n', f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print("Shape ban đầu:", e.shape)

f = e.reshape(3, 2)
print("Shape (3, 2):\n", f)

g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
print('reshape (3, 4):\n', g.reshape(3, 4))
print('reshape (3, 2, 2):\n', g.reshape(3, 2, 2))
print('reshape (2, 3, 2):\n', g.reshape(2, 3, 2))

[[1. 2. 3.]
 [4. 5. 6.]]
Shape ban đầu: (2, 3)
Shape (3, 2):
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
reshape (3, 4):
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2):
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2):
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [18]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print("Flatten mảng e:", f)

g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
j = g.flatten()
print("Flatten mảng g:", j)

Flatten mảng e: [1. 2. 3. 4. 5. 6.]
Flatten mảng g: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [19]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])

h_stack = np.hstack((f, g))
print('Horizontal Append:\n', h_stack)

v_stack = np.vstack((f, g))
print('Vertical Append:\n', v_stack)

Horizontal Append:
 [1. 2. 3. 4. 5. 6.]
Vertical Append:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [20]:
a = np.random.randint(100, size=(5,))
print('Random 1-D array:\n', a)

b = np.random.randint(100, size=(3, 4))
print('Random 2-D array:\n', b)

c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array:\n', c)

Random 1-D array:
 [47 57 21 38 52]
Random 2-D array:
 [[82 49 61 82]
 [91 19 89 76]
 [41 87 97 90]]
Random 3-D array:
 [[[42 73 13]
  [65 96 43]
  [ 6 24 23]
  [28 68 10]]

 [[13 52 58]
  [66 80 27]
  [34 48 95]
  [31 37 35]]

 [[63 22 14]
  [66  8 21]
  [81 45 15]
  [ 3 60  2]]]


In [23]:
a = np.random.normal(5, 0.5, 10)
print(a)

[4.73943123 4.71050883 5.0149381  4.03578622 5.57969006 4.42726408
 5.09976735 5.06763433 3.92074506 5.36486441]


In [24]:

a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print("1 giá trị ngẫu nhiên:", a)


b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3,5))
print("Ma trận 3x5 ngẫu nhiên:\n", b)

1 giá trị ngẫu nhiên: 10
Ma trận 3x5 ngẫu nhiên:
 [[16  4  2 20 14]
 [18 14 14  2  4]
 [ 6  8  6  8 14]]


In [25]:
# 3.8. Thay doi gia tri cua ma tran
#Tao ma tran 5 x 5 voi so 1
A = np.matrix(np.ones((5,5)))
print('The matrix ban đầu:\n', A)

np.array(A)[2] = 2
print('Thay đổi dòng 3 bằng np.array:\n', A)

np.asarray(A)[2] = 2
print('Thay đổi dòng 3 bằng np.asarray:\n', A)

The matrix ban đầu:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Thay đổi dòng 3 bằng np.array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Thay đổi dòng 3 bằng np.asarray:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
# Hàm arange
a = np.arange(1, 20)
print("Arange 1->19:", a)

b = np.arange(1, 20, 2)
print("Arange bước nhảy 2:", b)

# Hàm linspace (chia đều khoảng)
c = np.linspace(1., 5., num=10)
print("Linspace:", c)

Arange 1->19: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Arange bước nhảy 2: [ 1  3  5  7  9 11 13 15 17 19]
Linspace: [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [27]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print("Ma trận gốc:\n", a)

# Cắt theo dòng (slice)
print('first row:', a[0])
print('second row:', a[1])

# Cắt theo cột/phần tử (indexing)
print('Second column:', a[:, 1])
print('first column:', a[:, 0])
print('First two values of second row:', a[1, :2]) # Đã sửa để in ra đúng [4 5] như trong tài liệu

Ma trận gốc:
 [[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
first column: [1 4]
First two values of second row: [4 5]


In [29]:
# Tạo pandas series từ list
a = pd.Series([1., 2., 3.])
print(a)
print('First value:', a[0])

b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)
print('First value:', b['a'])

# Tạo pandas series từ dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64


In [30]:
# Numpy --> Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame: \n', df_h)

# Pandas --> Numpy
numpy_h = np.array(df_h)
print('Numpy array: \n', numpy_h)

DataFrame: 
    0  1
0  1  2
1  3  4
Numpy array: 
 [[1 2]
 [3 4]]


In [31]:
dic = {'Name': ['John', 'Smith'], 'Age': [30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)

    Name  Age
0   John   30
1  Smith   40


In [32]:
# tạo mảng 20x4
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head()) # in 5 dòng đầu tiên

        so1       so2       so3       so4
0  0.589783 -0.799177 -0.529551 -1.001829
1 -0.119037  1.797808 -0.799304  0.003133
2  2.511734 -0.534311 -0.807503  1.452578
3 -0.302975 -1.074337  2.008697 -1.274910
4  1.126758  1.045797 -0.387231  0.430110


In [33]:
# tạo mảng 20 x 4
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head()) # in 5 dòng đầu tiên

# chọn 1 cột
print('Chọn cột so1\n', df['so1'])

# chọn nhiều dòng
print('Chọn nhiều dòng\n', df[0:3])

# chọn nhiều cột
print('Chọn nhiều cột\n', df[['so1', 'so3']])

# chọn nhiều dòng, nhiều cột
print('Chọn nhiều dòng, nhiều cột\n', df.iloc[:3, 2])

# Xóa cột
df = df.drop(columns=['so1', 'so4'])
print(df)

        so1       so2       so3       so4
0 -0.282682 -0.211345 -1.524437 -0.608406
1  0.731014  0.826748 -0.118900 -2.726971
2 -0.998512 -1.165211  0.365742  0.746646
3  0.884696  0.330282 -0.788005  1.750690
4  0.334600  0.066807  0.890396  0.313670
Chọn cột so1
 0    -0.282682
1     0.731014
2    -0.998512
3     0.884696
4     0.334600
5    -0.102982
6    -0.901002
7    -0.390435
8    -0.458739
9     1.203206
10    0.660318
11   -0.296069
12    1.125064
13    1.081159
14    1.548784
15    0.030100
16    0.705830
17   -1.543403
18   -0.080611
19    0.620703
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0 -0.282682 -0.211345 -1.524437 -0.608406
1  0.731014  0.826748 -0.118900 -2.726971
2 -0.998512 -1.165211  0.365742  0.746646
Chọn nhiều cột
          so1       so3
0  -0.282682 -1.524437
1   0.731014 -0.118900
2  -0.998512  0.365742
3   0.884696 -0.788005
4   0.334600  0.890396
5  -0.102982  0.727185
6  -0.901002  0.294119
7  -0.390435 -0.144674


In [34]:
# Nối 2 DataFrame
df1 = pd.DataFrame({'Name': ['John', 'Smith', 'Paul'],
                    'Age': [25, 30, 50]}, index=[0, 1, 2])

df2 = pd.DataFrame({'Name': ['Adam', 'Smith'],
                    'Age': [26, 11]}, index=[3, 4])

df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)

# Xóa những giá trị ở cột Name trùng nhau
print('Drop duplicate values in DataFrame\n', df_concat.drop_duplicates('Name'))

# Sắp xếp theo cột
print('Sort values in DataFrame\n', df_concat.sort_values('Age'))

# Đổi tên cột
df_rename = df_concat.rename(columns={'Name': 'Surname', 'Age': 'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicate values in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


In [37]:
import pandas as pd

path = '/content/sample_data/california_housing_test.csv'


df_csv = pd.read_csv(path, skipinitialspace=True, index_col=False)


print(df_csv.head())


print(df_csv.shape)

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0  
(3000, 9)
